fos_user:
    db_driver: orm # valid values are 'orm', 'mongodb' and 'couchdb'
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: "noreply@mosite.fr"
        sender_name: "admin"

