security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:

        ROLE_CONTRIBUTEUR: ROLE_USER
        ROLE_MEMBRE: [ROLE_INTERNAUTE, ROLE_CONTRIBUTEUR]
        ROLE_MEMBRE_BUREAU: ROLE_MEMBRE
        ROLE_ADMIN: [ROLE_MEMBRE, ROLE_MEMBRE_BUREAU]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back-office/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_INTERNAUTE }
        - { path: ^/back-office/, role: ROLE_CONTRIBUTEUR }
        - { path: ^/back-office/, role: ROLE_MEMBRE }
        - { path: ^/back-office/, role: ROLE_MEMBRE_BUREAU }
#        - { path: ^/admin/, role: ROLE_ADMIN }